You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565
/home/khv4ky/.conda/envs/EasyEdit/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py:561: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(
Traceback (most recent call last):
  File "/home/khv4ky/toxicity/zeroshot_parallel_detox/embeddings/2-aya-8b.py", line 478, in <module>
    main()
  File "/home/khv4ky/toxicity/zeroshot_parallel_detox/embeddings/2-aya-8b.py", line 420, in main
    analyzer = TextAnalyzer(args.model_name, device=args.device)
  File "/home/khv4ky/toxicity/zeroshot_parallel_detox/embeddings/2-aya-8b.py", line 26, in __init__
    self.model = AutoModel.from_pretrained(model_name).to(self.device)
  File "/home/khv4ky/.conda/envs/EasyEdit/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3110, in to
    return super().to(*args, **kwargs)
  File "/home/khv4ky/.conda/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
  File "/home/khv4ky/.conda/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/home/khv4ky/.conda/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
  File "/home/khv4ky/.conda/envs/EasyEdit/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
  File "/home/khv4ky/.conda/envs/EasyEdit/lib/python3.9/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available
